version: "3.8"

services:
  app:
    build:
      context: .
    restart: always
    ports:
      - "${PORT:-4001}:4000"
    environment:
      PORT: 4000
      PHX_HOST: localhost
      # PHX_HOST: bluemarine.eu.ngrok.io
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DATABASE_URL: postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}

  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      # POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_MULTIPLE_DATABASES: ${DATABASE_NAME},${DATABASE_NAME}_dev

volumes:
  postgres-data:
